server:
  port: 8080

spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: kafka:9092
  eureka:
    client:
      service-url:
        defaultZone: http://eureka:8761/eureka/
