server:
  port: 8082

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
  eureka:
    client:
      service-url:
        defaultZone: http://eureka:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
  mail:
    host: smtp.yandex.ru
    port: 587
    username: makry32rus@yandex.ru
    password: uiveyltskjej****
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

resilience4j:
  circuitbreaker:
    instances:
      notificationServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
